export const pokemonBgColors = {
  normal: 'bg-normal',
  fire: 'bg-fire',
  water: 'bg-water',
  electric: 'bg-electric',
  grass: 'bg-grass',
  ice: 'bg-ice',
  fighting: 'bg-fighting',
  poison: 'bg-poison',
  ground: 'bg-ground',
  flying: 'bg-flying',
  psychic: 'bg-psychic',
  bug: 'bg-bug',
  rock: 'bg-rock',
  ghost: 'bg-ghost',
  dragon: 'bg-dragon',
  dark: 'bg-pokeDark',
  steel: 'bg-steel',
  fairy: 'bg-fairy',
};

export const pokemonFromColors = {
  normal: 'from-normal',
  fire: 'from-fire',
  water: 'from-water',
  electric: 'from-electric',
  grass: 'from-grass',
  ice: 'from-ice',
  fighting: 'from-fighting',
  poison: 'from-poison',
  ground: 'from-ground',
  flying: 'from-flying',
  psychic: 'from-psychic',
  bug: 'from-bug',
  rock: 'from-rock',
  ghost: 'from-ghost',
  dragon: 'from-dragon',
  dark: 'from-pokeDark',
  steel: 'from-steel',
  fairy: 'from-fairy',
};

export const pokemonToColors = {
  normal: 'to-normal',
  fire: 'to-fire',
  water: 'to-water',
  electric: 'to-electric',
  grass: 'to-grass',
  ice: 'to-ice',
  fighting: 'to-fighting',
  poison: 'to-poison',
  ground: 'to-ground',
  flying: 'to-flying',
  psychic: 'to-psychic',
  bug: 'to-bug',
  rock: 'to-rock',
  ghost: 'to-ghost',
  dragon: 'to-dragon',
  dark: 'to-pokeDark',
  steel: 'to-steel',
  fairy: 'to-fairy',
};
